# Generated by Django 2.2.2 on 2019-07-11 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=400)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
    ]
